### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Beard-Bois** [Harve/GoCreateModpack#1]
Hello!

I was wondering if your modpack had a Discord Server? If so, where/what is the link? If not, do you plan on starting one?

-SkinnyBois

**Comment by Harve** [comment]
Hi, SkinnyBois
I'm thinking of creating a discord server along with the release of the next big update 1.2.0.
I'm aiming for early July (So a week or two).
I'll let you know here, when I've made it.

**Comment by Harve** [comment]
Hello again!
I've created a Discord Server. Feel free to join here: https://discord.com/invite/Q2Ua8uYBym
