### ISSUE TITLE
Coding Issues in Abyss Chapter II 

### ISSUE THREAD

**Issue by TheNoobyTalker** [Harve/GoCreateModpack#10]
I do not know if this is known, as an issue for you.

Now one persistent issue that i had, while interacting with the abyss mod, was that the guide book seemed quite empty, aka pages that are unlocked, have no content. Aswell as that, at the bottom of the guide of the mod it said "parsing error".
As of now i have to see if downgrading to the latest release, does not have this error but nonetheless i'd suggest doing that in the next update and wait for a more stable abyss update.

EDIT: It seems to fix it as it no longer mentions the parsing error in the latest log, but causes some errors in kubejs

**Comment by Harve** [comment]
The Abyss guidebook is unfinished, hence why I take it from the player at the start of the game. Downgrading is a bad idea as players would have to start a new world. Issues with the abyss that do not concern custom recipes cannot be fixed by myself.

**Comment by TheNoobyTalker** [comment]
yeah ive only realized the effects that would have after i wrote it. But you could give more info on certain quests like the bosses if they require a specific ritual or condition.

Abyss aside i really enjoy your modpack. :)

**Comment by Harve** [comment]
Yeah, I'll definitely add more description. I was struggling myself to make sense of it.
