### ISSUE TITLE
Version 1.3.3 instability

### ISSUE THREAD

**Issue by DamondSword2247** [Harve/GoCreateModpack#11]
Crash report
[crash-2021-08-06_14.55.31-server.txt](https://github.com/Harve/GoCreateModpack/files/6947486/crash-2021-08-06_14.55.31-server.txt)

**Comment by DamondSword2247** [comment]
Almost forgot, I was doing absolutely nothing when the crash occurred I just sat in one place for about 10 minutes.

**Comment by Harve** [comment]
As I thought,  Go In to mowziesmobs-common.toml in config and setting line 478 to spawn_rate = 0 . This will be fixed in 1.4.0

**Comment by DamondSword2247** [comment]
Good to know

**Comment by Harve** [comment]
This has been fixed in 1.4.0
