### ISSUE TITLE
Game crashes repeatedly while exploring new world due to null entity vehicle

### ISSUE THREAD

**Issue by SheriffEllis** [Harve/GoCreateModpack#12]
While exploring a newly created world in singleplayer I have crashed multiple times with no apparent cause. Crash report seems to suggest there is a spider attempting to mount a non-existent vehicle.

Two examples of crash reports for the same issue in the same world.
[crash-2021-08-17_04.35.02-server.txt](https://github.com/Harve/GoCreateModpack/files/6996910/crash-2021-08-17_04.35.02-server.txt)
[crash-2021-08-17_04.16.57-server.txt](https://github.com/Harve/GoCreateModpack/files/6996911/crash-2021-08-17_04.16.57-server.txt)

**Comment by Harve** [comment]
Try updating the modpack to 1.4.2. What version of Java are you running as the crash report suggests it's quite an old one, I'd recommend updating it to OpenJDK

**Comment by SheriffEllis** [comment]
I have the latest version of oracle java (8, update 301), are you suggesting openjdk 16?

**Comment by Harve** [comment]
No, that version is fine. Update the modpack if you haven't already.

**Comment by SheriffEllis** [comment]
I have updated the pack to 1.4.2 but the issue persists:
[crash-2021-08-17_15.31.57-server.txt](https://github.com/Harve/GoCreateModpack/files/7000841/crash-2021-08-17_15.31.57-server.txt)

Would you like me to provide the world download? The crash can be recreated by simply standing still in the location for approximately 10 minutes.

**Comment by Harve** [comment]
Please post it in the Discord server as I am not available to fix anything til Sunday

**Comment by Harve** [comment]
Additionally, you could just delete that entity.

**Comment by SheriffEllis** [comment]
Killing all spiders in the area seems to have remedied the issue, though I can't speak to the cause of the original problem
