### ISSUE TITLE
Trojan File in Go Create?

### ISSUE THREAD

**Issue by Bosrosb** [Harve/GoCreateModpack#13]
When I tried to download Go Create 1.4.2, windows security told me there was a trojan file in the temp folder, but when I removed it, it didn't allow me to download it. Is there supposed to be a trojan file?

**Comment by Harve** [comment]
This is a false positive by Windows Defender and has been happening to loads of mods and modpacks from Curseforge. Manually updating Windows Defender should fix it https://www.microsoft.com/en-us/wdsi/defenderupdates

**Comment by Bosrosb** [comment]
oh all right, thank you
