### ISSUE TITLE
Shift key glitch

### ISSUE THREAD

**Issue by doodgy** [Harve/GoCreateModpack#14]
After 5min of play, I get the "shift key glitch". Shift key gets stuck and can't use inventory properly. Have to restart to fix the problem, then the problem repeats itself. Have tried all the fixes I could find online, to no avail.

**Comment by Harve** [comment]
What is the "shift key glitch". I've never heard of it before this. Please post your latest.log.

**Comment by doodgy** [comment]
It is where the shift key gets "stuck". Whenever an item is clicked in inventory, it does a shift click. So items go straight into hotbar. Cannot drag items. Minecraft doesn't crash, but can't craft properly craft because it performs a shift click. Character does not sneak when out of inventory. Interestingly when I try to change a control key, it also inputs shift. 
PS I have sticky keys disabled

**Comment by doodgy** [comment]
I was an idiot, managed to solve the issue!
