### ISSUE TITLE
Cannot download from the Curse Forge app

### ISSUE THREAD

**Issue by Dorrivix** [Harve/GoCreateModpack#15]
the pack gets up to "craft sense" (mod 170 out of 188) and deletes all previous download progress.

**Comment by Harve** [comment]
This is Curseforge being garbage. Try download the latest version and let me know.

**Comment by Harve** [comment]
Apparently this has been fixed by CurseForge. Please feel free to re-open this issue if it still occurs, however it would be better if you let CurseForge support in their discord server know as I cannot fix it.
