### ISSUE TITLE
Serveur ne marche pas

### ISSUE THREAD

**Issue by babane19fr** [Harve/GoCreateModpack#19]
Je ne comprends pas comment installer le mod pack sur un serveur OMGserv, j'ai lu les textes mais je n'y arrive pas

**Comment by Harve** [comment]
Run start-server.bat on Windows or start-server.sh on Linux.
It will download the files, then ask you to type "TRUE", it will then launch.
I'm closing this issue as it's not an issue with the modpack (and I don't speak French).
Please join the Discord if you need more help https://discord.gg/Q2Ua8uYBym
