### ISSUE TITLE
[1.2.0] Client crash on server join.

### ISSUE THREAD

**Issue by laserlemons** [Harve/GoCreateModpack#2]
I'm unsure what mod is causing this otherwise I'd report it on their page. It happens when I log into my server since 1.2.0. Doesn't happen on a newly generated world.

https://pastebin.com/dbp3mLGw

**Comment by Harve** [comment]
Seems to be an issue with Sodium Reforged. Try resetting your graphics settings by changing the Sodium-options.json file in config to this.

{
  "quality": {
    "cloud_quality": "DEFAULT",
    "weather_quality": "DEFAULT",
    "enable_vignette": true,
    "enable_fog": true,
    "enable_clouds": true,
    "smooth_lighting": "HIGH"
  },
  "advanced": {
    "use_vertex_array_objects": true,
    "use_chunk_multidraw": true,
    "translucency_sorting": true,
    "use_leaves_culling": false,
    "animate_only_visible_textures": true,
    "use_entity_culling": true,
    "use_particle_culling": true,
    "use_fog_occlusion": true,
    "use_compact_vertex_format": false,
    "use_block_face_culling": true,
    "allow_direct_memory_access": true,
    "ignore_driver_blacklist": false
  }
}

**Comment by laserlemons** [comment]
Still getting the crash. I assume it's a conflict with something specific in my base. It's weird that it'd only show up on 1.2.0.

**Comment by Harve** [comment]
I'm fairly sure it's Sodium Reforged causing the issue. Try removing or disabling it and let me know what happens.

**Comment by laserlemons** [comment]
Removing it or downgrading to the same version used in 1.1.3 fixed the crash. I'll report it to Sodium if someone hasn't already.

**Comment by Harve** [comment]
I'll take a look when I next get a chance to and might switch version as this is the second occurrence of this exact same issue.

**Comment by Harve** [comment]
Please create a new issue if this still occurs in 1.2.1 as downgrading will make More Villagers non functional.
