### ISSUE TITLE
[1.2.1] Client Crash On Server Join

### ISSUE THREAD

**Issue by laserlemons** [Harve/GoCreateModpack#3]
Crash Report:
https://pastebin.com/y4WYUnvr

This crash occurs when logging into or getting near my main base on my server. I can provide the world download if necessary.

Reverting to Sodium 2.4 or earlier fixes the issue.

I reported it to the Sodium issues page: https://github.com/spoorn/sodium-forge/issues/78

**Comment by Harve** [comment]
Does this part of the world have Eidolon stuff as there seems to be a couple issues related to Eidolon on their issues page.

**Comment by Harve** [comment]
If this issue relates to what I believe, it should be fixed in 1.3.0. However if it still remains please create a new issue

**Comment by laserlemons** [comment]
It was fixed for me in 1.3.0. FYI the author of sodium fixed the bug today.
