### ISSUE TITLE
Crash information follow-up survey

### ISSUE THREAD

**Issue by Fzoss** [Harve/GoCreateModpack#6]
There have been 31 crashes in the last 72 hours, all of which have been compressed in a file that I hope will help you.

_Originally posted by @Harve in https://github.com/Harve/GoCreateModpack/issues/5#issuecomment-880501294_
I believe I've found the source of a few of the crashes, however I cannot find out what is going on unless you provide the crash logs

**Comment by Fzoss** [comment]
[crash-reports.zip](https://github.com/Harve/GoCreateModpack/files/6821538/crash-reports.zip)
 I upload the file here. @Harve

**Comment by Harve** [comment]
I have had a look through and most of these seem to point to a Create contraption at  12596.00, 69.00, -1119.00.

**Comment by Fzoss** [comment]
Unfortunately, anyone approaching this location currently causes an immediate server crash, which was normal an hour ago, so I can't confirm exactly what's happening.

**Comment by Fzoss** [comment]
I should be able to restore the world by backing up to confirm exactly what happened, but this will cause all recent worlds changes to disappear.

**Comment by Harve** [comment]
Please let me know by opening a new issue if this still occurs in 1.3.0. Please ensure you have cleared up whatever was at the provided coords as that seems to be the source of non Server watchdog crashes
