### ISSUE TITLE
X Error of failed request:  BadLength

### ISSUE THREAD

**Issue by StevenDoesStuffs** [Harve/GoCreateModpack#7]
OS: Arch Linux
Modpack version: `1.3.0`
Java version: OpenJDK version `1.8.0_292`
Graphics: GTX 1060 3GB with driver version `465.31-14`
Misc other system info: xorg version `1.20.12-1`, plasma-desktop version `5.22.3-1`

I'm currently experiencing a crash while trying to launch the client:
```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Serial number of failed request:  319
  Current serial number in output stream:  319
```

It seems like [someone else](https://www.curseforge.com/minecraft/modpacks/go-create?comment=59) is having a similar issue as well. 

Here is the full [debug log](https://gist.github.com/StevenDoesStuffs/2c1c6a3b6ae53d758aaf02b9a3f15695).

EDIT: disabling the mod "It's the little things" fixes the issue

**Comment by Harve** [comment]
I will put a note on the page informing users to disable ITLT if they are using Linux
