### ISSUE TITLE
Some quest rewards have the old intergrated circuits

### ISSUE THREAD

**Issue by MalachiAzrael** [Harve/GoCreateModpack#8]
![2021-07-18_18 28 39](https://user-images.githubusercontent.com/59282225/126076709-75fd7fd1-db2f-4142-8499-b5ff79459b7b.png)

**Comment by Harve** [comment]
Damn, I knew there was going to be one. I'll fix it in the next update I release

**Comment by Harve** [comment]
Fixed in 1.3.2
