### ISSUE TITLE
Frequent lagspikes after crash

### ISSUE THREAD

**Issue by TheNoobyTalker** [Harve/GoCreateModpack#9]
Now after a crash, that happened randomly while playing, i get lag spikes every 3-6 seconds that go down from ~160 fps to about 20 fps and that was rarely the case before that.
Currently i have allocated ~4.8 gigabytes of RAM currently and my game, like aforementioned, was working.
There were freezes sometimes, so i don't know whats going on.

Crashlog put it in here:
[crash-2021-07-27_22.09.18-server.txt](https://github.com/Harve/GoCreateModpack/files/6888544/crash-2021-07-27_22.09.18-server.txt)

**Comment by Harve** [comment]
Try removing Sodium Reforged from both client and server. I will be removing it in the next update

**Comment by TheNoobyTalker** [comment]
Ok ill remove it to see if that was the cause

**Comment by Harve** [comment]
I've removed Sodium and fixes a lot of issues, please let me know if this still occurs in 1.3.3 by re-opening this issue or making a new one.
